//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bans
    {
        public int ID { get; set; }
        public string Login { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
