//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearingSchedule
    {
        public int ID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
